name: Sync sunnypilot/tn

on:
  schedule:
    - cron: '0 10 * * *'  # 每天 UTC 时间 10:00 自动运行
  workflow_dispatch:        # 支持手动触发

jobs:
  sync-tn-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo default branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 拉取完整历史

    - name: Add upstream remote and fetch tn branch
      run: |
        git remote add upstream https://github.com/sunnypilot/sunnypilot.git
        git fetch upstream tn

    - name: Create or reset tn branch to upstream/tn
      run: |
        git checkout -B tn upstream/tn

    - name: Push tn branch to your repo
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} tn --force
