name: Sync sunnypilot/tn

on:
  schedule:
    - cron: '0 10 * * *'  # 每天 UTC 时间 10:00 自动运行
  workflow_dispatch:        # 支持手动触发

jobs:
  sync-tn-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo tn branch
      uses: actions/checkout@v3
      with:
        ref: tn
        fetch-depth: 0  # 完整拉取历史方便推送

    - name: Add upstream remote for sunnypilot
      run: |
        git remote add upstream https://github.com/sunnypilot/sunnypilot.git
        git fetch upstream tn

    - name: Reset local tn branch to upstream tn branch
      run: |
        git checkout tn
        git reset --hard upstream/tn

    - name: Push changes to your repo tn branch
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} tn --force
